apiVersion: bundle.gravitational.io/v2
kind: SystemApplication
metadata:
  name: bandwagon
  resourceVersion: "0.0.0"
  namespace: kube-system
hooks:
  install:
    job: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: bandwagon-install
      spec:
        template:
          metadata:
            name: bandwagon-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: debian-tall
                image: quay.io/gravitational/debian-tall:0.0.1
                command:
                  - /usr/local/bin/kubectl
                  - create
                  - -f
                  - /var/lib/gravity/resources/install.yaml
