apiVersion: v1
kind: Service
metadata:
  name: bandwagon
  namespace: kube-system
  labels:
    app: bandwagon
spec:
  selector:
    app: bandwagon
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bandwagon
  namespace: kube-system
  labels:
    app: bandwagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bandwagon
  template:
    metadata:
      labels:
        app: bandwagon
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      tolerations:
        - key: "gravitational.io/runlevel"
          value: system
          operator: Equal
      securityContext:
        runAsUser: -1
      containers:
        - name: bandwagon
          image: bandwagon:0.0.0
          ports:
            - containerPort: 8000
          env:
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
          volumeMounts:
            - name: bin
              mountPath: /opt/bin
            - name: gravity
              mountPath: /var/lib/gravity/local
      volumes:
        - name: bin
          hostPath:
            path: /usr/bin
        - name: gravity
          hostPath:
            path: /var/lib/gravity/local
