apiVersion: v1
kind: Service
metadata:
  name: bandwagon
  namespace: kube-system
  labels:
    app: bandwagon
spec:
  selector:
    app: bandwagon
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: bandwagon
  namespace: kube-system
  labels:
    app: bandwagon
spec:
  containers:
    - name: bandwagon
      image: bandwagon:1.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
